//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudioGlumeScena.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Grupa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Grupa()
        {
            this.Ucenik = new HashSet<Ucenik>();
        }
    
        public int BrojGrupe { get; set; }
        public string VremeCasa { get; set; }
        public string DanOdrzavanjaCasa { get; set; }
        public string AktivniZadatak { get; set; }
        public string JMBGp { get; set; }
        public string NazivOpstine { get; set; }
    
        public virtual Lokacija Lokacija { get; set; }
        public virtual Profesor Profesor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ucenik> Ucenik { get; set; }
    }
}
