//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudioGlumeScena.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ucenik
    {
        public string JMBGu { get; set; }
        public string Ime { get; set; }
        public string Prezime { get; set; }
        public int GodinaRodjenja { get; set; }
        public string BrTelefona { get; set; }
        public string Adresa { get; set; }
        public string PoslednjaPlacenaClanarina { get; set; }
        public string Email { get; set; }
        public int BrojGrupe { get; set; }
        public string Password { get; set; }
    
        public virtual Grupa Grupa { get; set; }
    }
}
